export const SIGN_IN = 'SIGN_IN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN ';
export const ERROR = 'ERROR';
export const LOG_OUT = 'LOG_OUT';
export const LOADING_LOGIN = 'LOADING_LOGIN';

export const SELECT_COMPANY = 'SELECT_COMPANY';
export const RELOAD_COMPANY = 'RELOAD_COMPANY';
export const REFRESH_IDCONNECTION = 'REFRESH_IDCONNECTION';


//signalr =====================================

export const ARBOL = 'ARBOL';
export const TREE_PARTS = 'TREE_PARTS';
export const DATA_GENERAL = 'DATA_GENERAL';
export const ID_DATA_TABLE = 'ID_DATA_TABLE';
export const TREE_COUNT = 'TREE_COUNT';
export const LISTAR_POR_PERIODO = 'LISTAR_POR_PERIODO';
export const PROJECT_DETAILS = 'PROJECT_DETAILS';
export const LIST_HISTORY = 'LIST_HISTORY';

export const LIMPIA_PARTY_CONTROL = 'LIMPIA_PARTY_CONTROL';
export const PARTY_CONTROL = 'PARTY_CONTROL';
export const PARTY_CONTROL22 = 'PARTY_CONTROL22';
export const PARTY_CONTROL1 = 'PARTY_CONTROL1';

export const LISTAR_SUBS = 'LISTAR_SUBS';
export const LIMPIAR_SUBS = 'LIMPIAR_SUBS';

export const LISTAR_CLIENTES = 'LISTAR_CLIENTES';
export const LISTAR_UBICACIONES = 'LISTAR_UBICACIONES';
export const LIMPIAR_UBICACIONES = 'LIMPIAR_UBICACIONES';

export const LISTAR_MODELOS = 'LISTAR_MODELOS';

export const LISTAR_MONEDAS = 'LISTAR_MONEDAS';

export const LISTAR_UNIDADES = 'LISTAR_UNIDADES';

export const RECOGER_ITEMS = 'RECOGER_ITEMS';
export const LIMPIAR_ITEMS = 'LIMPIAR_ITEMS';

export const DELETE_ITEM = 'DELETE_ITEM';



export const LEER_PRESUPUESTO = 'LEER_PRESUPUESTO';
export const ACT_PRESUPUESTO = 'ACT_PRESUPUESTO';

export const CAMBIA_SELECCION = 'CAMBIA_SELECCION';
export const SUB_SEL = 'SUB_SEL';


export const MENSUAL_DETALLE = 'MENSUAL_DETALLE';
export const APU_DETALLE = 'APU_DETALLE';

export const APU_DETALLE_CATALOGO = 'APU_DETALLE_CATALOGO';
export const APU_DETALLE_CATALOGO1 = 'APU_DETALLE_CATALOGO1';
export const APU_DETALLE_CATALOGO2 = 'APU_DETALLE_CATALOGO2';
export const APU_DETALLE_CATALOGO_SUBP = 'APU_DETALLE_CATALOGO_SUBP';

export const METRADO_DETALLE = 'METRADO_DETALLE';
export const METRADO_LIMPIAR = 'METRADO_LIMPIAR';

export const UNIQUE_DETALLE = 'UNIQUE_DETALLE';

export const ASOCIADO_DETALLE = 'ASOCIADO_DETALLE';
export const ESTRUCTURA_DETALLE = 'ESTRUCTURA_DETALLE';
export const CALCULO_DETALLE = 'CALCULO_DETALLE';
export const CALCULODET_DETALLE = 'CALCULODET_DETALLE';

export const NAVIGATION_TREE = 'NAVIGATION_TREE';
export const NAVIGATION_TREE_PC = 'NAVIGATION_TREE_PC';
export const ID_PC = 'ID_PC';

export const URN_WEB = 'URN_WEB';
export const URN_WEB1 = 'URN_WEB1';

export const PROJECT_LIST_DETAILS = 'PROJECT_LIST_DETAILS';
export const TREE_SELECTEDS = 'TREE_SELECTEDS';

export const AGREGA_REGISTRO = 'AGREGA_REGISTRO';

export const AGREGA_CATEGORIA = 'AGREGA_CATEGORIA';
export const AGREGA_TIPO = 'AGREGA_TIPO';
export const AGREGA_FAMILIA = 'AGREGA_FAMILIA';
export const AGREGA_ELEMENTOS = 'AGREGA_ELEMENTOS';


export const AGREGA_CATEGORIAB = 'AGREGA_CATEGORIAB';
export const AGREGA_TIPOB = 'AGREGA_TIPOB';
export const AGREGA_FAMILIAB = 'AGREGA_FAMILIAB';

export const ADD_CALCULO = 'ADD_CALCULO';
export const UPDATE_CALCULO = 'UPDATE_CALCULO';

export const ADD_CALCULODET = 'ADD_CALCULODET';
export const UPDATE_CALCULODET = 'UPDATE_CALCULODET';
export const DELETE_CALCULODET = 'DELETE_CALCULODET';

export const ADD_ASOCIADO = 'ADD_ASOCIADO';
export const CODIGO_OBTENIDO = 'CODIGO_OBTENIDO';
export const CODIGO_OBTENIDO1 = 'CODIGO_OBTENIDO1';

export const CODIGO_OBTENIDO_TITULO = 'CODIGO_OBTENIDO_TITULO';
export const CODIGO_OBTENIDO_TITULO1 = 'CODIGO_OBTENIDO_TITULO1';

export const DELETE_ASOCIADO = 'DELETE_ASOCIADO';
export const ASOCIADO_LIMPIAR = 'ASOCIADO_LIMPIAR';

export const ADD_ESTRUCTURA = 'ADD_ESTRUCTURA';
export const DELETE_ESTRUCTURA = 'DELETE_ESTRUCTURA';
export const UPDATE_ESTRUCTURA = 'UPDATE_ESTRUCTURA';

export const UPDATE_ASOCIADO = 'UPDATE_ASOCIADO';

export const UPDATE_METRADO = 'UPDATE_METRADO';

export const ESTABLECE_METRADO = 'ESTABLECE_METRADO';
export const ADD_METRADO = 'ADD_METRADO';
export const DELETE_METRADO = 'DELETE_METRADO';

export const AGREGA_GRUPO = 'AGREGA_GRUPO';
export const MODIFICA_GRUPO = 'MODIFICA_GRUPO';
export const ELIMINA_GRUPO = 'ELIMINA_GRUPO';

export const ELIMINA_GRUPOSUB = 'ELIMINA_GRUPOSUB';

export const MODIFICA_SUB = 'MODIFICA_SUB';
export const MODIFICA_SUB1 = 'MODIFICA_SUB1';
export const AGREGA_SUB1 = 'AGREGA_SUB1';

export const PONER_PROPS = 'PONER_PROPS';
export const CAMBIAR_FILA_ASOCIADO = 'CAMBIAR_FILA_ASOCIADO';

export const LISTAR_TITULOS = 'LISTAR_TITULOS';
export const LISTAR_TITULOS1 = 'LISTAR_TITULOS1';

export const LISTAR_PARTIDAS = 'LISTAR_PARTIDAS';

export const DETALLE_PRECIOS = 'DETALLE_PRECIOS';
export const LIMPIAR_DETALLE_PRECIOS = 'LIMPIAR_DETALLE_PRECIOS';

export const LISTAR_PARTIDAS1 = 'LISTAR_PARTIDAS1';


export const LISTAR_PARTIDASC = 'LISTAR_PARTIDASC';
export const LISTAR_PARTIDAS2 = 'LISTAR_PARTIDAS2';


export const LISTAR_PARTIDASC1 = 'LISTAR_PARTIDASC1';
export const LISTAR_PARTIDAS21 = 'LISTAR_PARTIDAS21';

export const LISTAR_PARTIDASC2 = 'LISTAR_PARTIDASC2';
export const LISTAR_PARTIDAS22 = 'LISTAR_PARTIDAS22';

export const ESTABLECER_PARTIDAS = 'ESTABLECER_PARTIDAS';
export const ESTABLECER_TITULOS = 'ESTABLECER_TITULOS';
export const UPDATE_PARTIDAS = 'UPDATE_PARTIDAS';
export const ADD_PARTIDAS = 'ADD_PARTIDAS';
export const DELETE_PARTIDAS = 'DELETE_PARTIDAS';

export const UPDATE_RECURSOS = 'UPDATE_RECURSOS';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const ESTABLECE_ITEM = 'ESTABLECE_ITEM';

export const LEER_PARTIDA = 'LEER_PARTIDA';
export const LEER_PARTIDA1 = 'LEER_PARTIDA1';
export const LEER_TITULO = 'LEER_TITULO';
export const LEER_TITULO1 = 'LEER_TITULO1';

export const LEER_RECURSO = 'LEER_RECURSO';
export const LEER_RECURSO1 = 'LEER_RECURSO1';

export const CODIGO_OBTENIDO_RECURSO = 'CODIGO_OBTENIDO_RECURSO';
export const CODIGO_OBTENIDO_RECURSO1 = 'CODIGO_OBTENIDO_RECURSO1';


export const ADD_RECURSOS = 'ADD_RECURSOS';
export const DELETE_RECURSOS = 'DELETE_RECURSOS';

export const UPDATE_TITULOS = 'UPDATE_TITULOS';
export const ADD_TITULOS = 'ADD_TITULOS';
export const DELETE_TITULOS = 'DELETE_TITULOS';

export const ADD_FAVORITO = 'ADD_FAVORITO';
export const DELETE_FAVORITO = 'DELETE_FAVORITO';

export const PIDE_ELEMENTOS_ITEMS = 'PIDE_ELEMENTOS_ITEMS';
export const LIMPIA_ELEMENTOS_ITEMS = 'LIMPIA_ELEMENTOS_ITEMS';
export const ESTABLECE_PARTIDAS = 'ESTABLECE_PARTIDAS';

export const ITEM_SELEC = 'ITEM_SELEC';

export const LISTAR_RECURSOS = 'LISTAR_RECURSOS';
export const LISTAR_RECURSOS1 = 'LISTAR_RECURSOS1';
export const LIMPIAR_RECURSOS = 'LIMPIAR_RECURSOS';

export const LISTAR_GRP_PARTIDAS = 'LISTAR_GRP_PARTIDAS';
export const LISTAR_GRP_PARTIDASN2 = 'LISTAR_GRP_PARTIDASN2';
export const LISTAR_GRP_PARTIDASN3 = 'LISTAR_GRP_PARTIDASN3';
export const LISTAR_GRP_PARTIDASN4 = 'LISTAR_GRP_PARTIDASN4';
export const LISTAR_GRP_PARTIDASN5 = 'LISTAR_GRP_PARTIDASN5';
export const LIMPIAR_GRP_PARTIDAS = 'LIMPIAR_GRP_PARTIDAS';

export const LISTAR_GRP_TITULOS = 'LISTAR_GRP_TITULOS';
export const LISTAR_GRP_TITULOSN2 = 'LISTAR_GRP_TITULOSN2';

export const LIMPIAR_GRP_TITULOS = 'LIMPIAR_GRP_TITULOS';


export const LIMPIAR_GRP_RECURSOS = 'LIMPIAR_GRP_RECURSOS';
export const LISTAR_GRP_RECURSOS = 'LISTAR_GRP_RECURSOS';
export const LISTAR_GRP_RECURSOSN2 = 'LISTAR_GRP_RECURSOSN2';
export const LISTAR_GRP_RECURSOSN3 = 'LISTAR_GRP_RECURSOSN3';

export const LEER_ARBOL_SUBPARTIDAS = 'LEER_ARBOL_SUBPARTIDAS';